runtime: nodejs10
handlers:
  # Serve all static files with urls ending with a file extension
- url: /(.*\..+)$ 
  static_files: docs/\1
  upload: docs/(.*\..+)$
  # catch all handler to index.html
- url: /.*
  static_files: docs/index.html #dist/index.html
  upload: docs/index.html #dist/index.html