pipelines:
  default:
    - step:
        name: Google App Engine
        script:
        - pipe: atlassian/google-app-engine-deploy:0.7.4
          variables:
            KEY_FILE: $KEY_FILE
            PROJECT: $PROJECT